### ISSUE TITLE
multiple items in "item_details" not working

### ISSUE THREAD

**Issue by sgpagek** [dycodedev/veritrans-node#1]
As stated in VeriTrans API Documentations, for multiple items inside item_details is supported by having them inside array like the following:
"item_details" : [{/*item1*/}, {/*item2*/}, ...]

However, this module does not seem to support the multiple items inside "item_details" and that appears in the validate_transaction.js file, which does not consider the possibility of having "item_details" in array format.

if (utils.hasProperty(payload, 'item_details')) {
            if (!utils.hasProperty(payload.item_details, requiredItemDetailsProps)) {
                return callback(new Error('item_details field requires: ' + requiredItemDetailsProps + ' fields'));
            }
        }

Edit:
Further code review seems to indicate the array fails at the following lines:
        if (object.constructor !== Object) {
            return false;
        }

at utils.js

**Comment by alwint3r** [comment]
Hello,

You were right, the problem lies in the following code:

```js
if (object.constructor !== Object) {
    return false;
}
```

I'll merge #2 soon.

**Comment by alwint3r** [comment]
It's merged. Thank you

**Comment by sgpagek** [comment]
Thanks for making this module :)

Kind Regards,
Pascal Gekko
