### ISSUE TITLE
syntaxerror: use of const in strict mode

### ISSUE THREAD

**Issue by sgpagek** [dycodedev/veritrans-node#3]
Hello,

The module works fine when I am in localhost. However, when I am running it on my AWS Machine, it shows error:
syntaxerror: use of const in strict mode

Complete error message as below:
/home/ubuntu/finhop/node_modules/veritrans/index.js:3
const _ = require('lodash');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

I tried running it on different environment and I use the simple: "node app.js" command to run it. 

Any clue? Does this happen to you or anyone else?

**Comment by alwint3r** [comment]
Hi,

This module is expected to be working on Node with version 4.x.x and 0.12.x
with --harmony runtime flag. What is the version on your AWS machine?

Best regards,
Alwin Arrasyid

**Comment by sgpagek** [comment]
Hi,

I am using Express 4.13.4 and Node 0.10.25 and I have tried with --harmony flag also.
The Node version could be the reason. Let me try to update my node version and I will get back to you.

Thanks!

**Comment by sgpagek** [comment]
Hi, I updated my Node version to v5.60 and the error goes away. Thanks!
