### ISSUE TITLE
404 - Error: The requested resource is not found

### ISSUE THREAD

**Issue by yogieputra8** [dycodedev/veritrans-node#5]
Saya coba bikin simple app pake ExpressJS manfaatin lib ini untuk check status dari orderan saya yg sudah sukses masuk ke Veritrans via Sandbox, berikut code saya:
```
var PORT = 4040;
var serverKey = "-SERVERKEY-";
var clientKey = "-CLIENTKEY-";
var url = "https://api.sandbox.veritrans.co.id/v2";


const config2 = {
    serverKey: serverKey,
    clientKey: clientKey,
    url: url
};
const Veritrans = require('veritrans');
const vt = new Veritrans(config2);

var http = require('http');
var express = require('express');
var bodyParser = require('body-parser');
var app = express();

app.use(bodyParser.json());
app.use(express.static(__dirname + '/public')); 
app.use(bodyParser.json());

app.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    next();
});


app.get('/status/:id', function(req, res) {
    var id = req.params.id;
    console.log(id)

    vt.transaction.status(id, (err, result) => {
        if (err) {
            console.error(err);
            return res.redirect('/transaction/' + id);
        }
        return res.redirect('/transaction/' + id);
    });
});

app.listen(PORT, function() {
    console.log('Express listening on port ' + PORT + '!');
});
```

Lalu saya coba GET Request via Postman
```http://localhost:4040/status/100030002_prepaid_1462182481 ```
Di Console saya keluar error:
```{ [Error: The requested resource is not found] code: '404' }```
Padahal orderID ini ada di Sandbox nya
<a href='http://postimg.org/image/volb9y0sx/' target='_blank'><img src='http://s32.postimg.org/volb9y0sx/Screen_Shot_2016_05_02_at_11_24_14_PM.jpg' border='0' alt="Screen Shot 2016 05 02 at 11 24 14 PM" /></a>

Ini kenapa ya? Apakah saya ada yang kelewatan?

**Comment by alwint3r** [comment]
Barusan saya coba pakai method yang sama dengan order id yang ada di akun sandbox saya dan berhasil. Apakah ada order id yang lain yang bisa dicoba?

**Comment by yogieputra8** [comment]
Hm, aneh. Apakah format orderID saya salah ya?

Ada pak, beberapa sample orderID lainnya
```100030001_prepaid_1462222122
100030001_prepaid_1462221624
100030002_prepaid_1462207258
100030001_20160219_004740```

**Comment by yogieputra8** [comment]
Code-nya saya tweak sedikit supaya bisa tampilin hasilnya jika sukses dan agar tidak redirect ke /transaction/ dan ternyata berhasil. Berikut hasil tweaks-nya..

```
app.get('/status/:id', function(req, res) {
    var id = req.params.id;
    console.log(id)

    vt.transaction.status(id, (err, result) => {
        if (err) {
            console.error(err);
            return res.redirect('/transaction/' + id);
        }

        // return res.redirect('/transaction/' + id);
        console.log(result)  
        res.status(200)
        res.setHeader('content-type', 'application/json');
        res.send(JSON.stringify(result));
    });
});
```
Saya masih belum ketemu kenapa redirect ke /transaction/ selalu error 404.
By the way, Terima kasih atas responnya pak.

**Comment by alwint3r** [comment]
Mungkin di app nya tidak ada route ke URI `/transaction/:id` jadi hasilnya error.
