### ISSUE TITLE
[Question] JSCS has merged with ESLint!

### ISSUE THREAD

**Issue by ikhsanalatsary** [dycodedev/veritrans-node#8]
because JSCS merged with ESLINT, So this repo need update standardization. right?

**Comment by alwint3r** [comment]
Correct, I assume standardization means the code styling rule. Fortunately, we have our own ESLint config which you can use as well by installing `eslint-config-dycode` package. We are going to update the code in this repo to comply with that config.

**Comment by ikhsanalatsary** [comment]
oh, good. if you have your own config. i just want to pull request with eslint-config-standard or standard JS (https://standardjs.com/)
